import type { NextPage, GetServerSidePropsContext } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import Sidebar from "~/components/Sidebar";
import NoteList from "~/components/NoteList";
import { getServerAuthSession } from "~/server/auth";
import { useState } from "react";
import type { Collection } from "@prisma/client";

const Home: NextPage = () => {
  const [selectedCollection, setSelectedCollection] =
    useState<Collection | null>(null);

  const handleCollectionSelect = (collection: Collection | null) => {
    setSelectedCollection(collection);
  };

  return (
    <>
      <Head>
        <title>T3 Note app</title>
        <meta
          name="description"
          content="Note app generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <main className="flex min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <Sidebar
            selectedCollection={selectedCollection}
            handleCollectionSelect={handleCollectionSelect}
          />
          <NoteList selectedCollection={selectedCollection} />
        </main>
      </>
    </>
  );
};

export default Home;

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const session = await getServerAuthSession(ctx);
  if (!session?.user) {
    return {
      redirect: {
        destination: "/sign-in",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
